version: '3'
services:
  db:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: e-jan
      POSTGRES_DB: library
    volumes:
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' 
